# Generated by Django 4.2 on 2023-04-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='bookapp/covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default=1, upload_to='bookapp/pdfs'),
            preserve_default=False,
        ),
    ]
