# Generated by Django 4.1.7 on 2023-04-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_cover_book_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
